apiVersion: v1
kind: Service
metadata:
  name: architect-chatbot
  namespace: eshop
  labels:
    app: architect-chatbot
spec:
  type: LoadBalancer
  selector:
    app: architect-chatbot
  ports:
  - name: http
    port: 80
    targetPort: 7860
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
